<?php
/**
 * @category    Inchoo
 * @package     Inchoo_KISSmetrics
 * @author      Branko Ajzele <ajzele@gmail.com>
 * @copyright   Copyright (c) Inchoo
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">_kmq.push(['record', '<?php echo $this->__('Catalog Product View (Any)') ?>', <?php echo $this->getJsonProductInfo() ?>]);</script>